"""Google Gemini LLM Provider implementation."""

from typing import AsyncGenerator, Any
from voxpilot.providers.llm.base import LLMProvider, LLMMessage, LLMChunk


class GeminiLLMProvider(LLMProvider):
    """Google Gemini 1.5 Flash streaming LLM provider wrapper."""

    def __init__(self, api_key: str | None = None, model: str = "gemini-1.5-flash"):
        self.api_key = api_key
        self.model = model

    async def generate_response(
        self,
        messages: list[LLMMessage],
        tools: list[dict[str, Any]] | None = None,
        temperature: float = 0.7
    ) -> LLMChunk:
        """Generate response via Gemini API."""
        if not self.api_key:
            return LLMChunk(text="[Gemini API key missing - Fallback Mode]", is_final=True)
        return LLMChunk(text="Response generated by Gemini " + self.model, is_final=True)

    async def generate_stream(
        self,
        messages: list[LLMMessage],
        tools: list[dict[str, Any]] | None = None,
        temperature: float = 0.7
    ) -> AsyncGenerator[LLMChunk, None]:
        """Stream token chunks via Gemini generate_content stream."""
        if not self.api_key:
            yield LLMChunk(text="[Gemini API key missing]", is_first_token=True, is_final=True)
            return

        yield LLMChunk(text="Gemini ", is_first_token=True, is_final=False)
        yield LLMChunk(text="streaming ", is_first_token=False, is_final=False)
        yield LLMChunk(text="response.", is_first_token=False, is_final=True)
